# Generated by Django 5.2.4 on 2025-08-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percent_off', models.PositiveIntegerField()),
                ('duration', models.CharField(choices=[('once', 'Once'), ('repeating', 'Repeating'), ('forever', 'Forever')], default='once', max_length=10)),
                ('stripe_coupon_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount'),
        ),
    ]
