# Generated by Django 5.2.4 on 2025-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_tax_alter_discount_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
