# Generated by Django 5.2.4 on 2025-08-02 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_orderitem_options_alter_discount_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percent off'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percentage of tax'),
        ),
    ]
