# Generated by Django 5.2.4 on 2025-08-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_discount_percent_off_alter_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='inclusive',
        ),
    ]
