# Generated by Django 5.2.4 on 2025-08-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_discount_currency_tax_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='currency',
        ),
    ]
