# Generated by Django 5.2.4 on 2025-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_tax_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', max_length=3),
        ),
    ]
